#!/usr/bin/env python3
"""Turn a light-on-dark logo (e.g. tools/art/birdlab-logo.png) into an 8-bit alpha
mask header, so the firmware can tint it and blend it onto any theme.
  python3 gen_logo.py <in.png> <height_px> <c_name> <out.h>"""
import sys
from PIL import Image, ImageOps

src, height, name, out = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]
im = Image.open(src).convert("L")                 # brightness = coverage (white logo on black)
bbox = im.point(lambda v: 255 if v > 40 else 0).getbbox()
im = im.crop(bbox)
w = round(im.width * height / im.height)
im = im.resize((w, height), Image.LANCZOS)
im = ImageOps.autocontrast(im, cutoff=1)          # full 0..255 range after resampling
data = im.tobytes()
with open(out, "w") as f:
    f.write(f"// {name}: generated by tools/gen_logo.py from {src.split('/')[-1]} — do not edit.\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write(f"#define {name.upper()}_W {w}\n#define {name.upper()}_H {height}\n")
    f.write(f"static const uint8_t {name}[{w * height}] = {{\n")
    for i in range(0, len(data), 32):
        f.write("  " + ",".join(str(b) for b in data[i:i + 32]) + ",\n")
    f.write("};\n")
print(f"{name}: {w}x{height} -> {out}")
